import { PlatformRaw, ServiceRaw, NetworkId } from "../types";
export const platform: PlatformRaw = {
  id: "btcsol",
  name: "btcSOL",
  description:
    "btcSOL enables Solana token holders to stake their SOL and accumulate BTC daily. The BTC rewards you earn come from the on-chain yield generated by your staked SOL, which automatically purchases zBTC.",
  tags: ["dapp"],
  links: {
    website: "https://btcsol.co/",
    discord: "https://discord.com/invite/zeusnetwork",
    twitter: "https://x.com/btcsol_co",
    documentation: "https://docs.btcsol.co/",
  },
  tokens: ["BSoLov7Es6mGLkBq7Z89PSWDmk6Vsw4jVxdfE2UHrJTX"],
};

const earnContract = {
  name: "Earn",
  address: "SYNMjud3ALEaeJhxuq8gpc2wJzC4XLHfxp9SgKmzQ8r",
  networkId: NetworkId.solana,
};

const earnService: ServiceRaw = {
  id: `${platform.id}-earn`,
  name: "Earn",
  platformId: platform.id,
  contractsRaw: [earnContract],
};

export const services: ServiceRaw[] = [earnService];
